### ISSUE TITLE
rixrix, can you release 1.0.0 to npm?

### ISSUE THREAD

**Issue by the-real-blackh** [SodiumFRP/sodium-typescript#26]
Hi Richard, could you do your thing of releasing to npm again? Also, please tell me how you did it and give me the necessary keys, and so on. Thanks!

Incidentally, when I type 'npm run prerelease' I'm getting this error message:

ash: 80d441bc6cf3bfc10c15  
Version: webpack 1.15.0
Time: 359ms
    + 1 hidden modules

ERROR in ./src/lib/Sodium.ts
Module build failed: TypeError: Cannot read property 'exclude' of undefined
    at applyDefaults (/home/blackh/src/sodium-typescript/node_modules/awesome-typescript-loader/src/instance.ts:267:72)
    at Object.ensureInstance (/home/blackh/src/sodium-typescript/node_modules/awesome-typescript-loader/src/instance.ts:146:5)
    at compiler (/home/blackh/src/sodium-typescript/node_modules/awesome-typescript-loader/src/index.ts:39:20)
    at Object.loader (/home/blackh/src/sodium-typescript/node_modules/awesome-typescript-loader/src/index.ts:20:18)

**Comment by rixrix** [comment]
@the-real-blackh I'm doing it now - I've got the fix to that error. Let me do a couple of testing and will push the fix and update npm. cheers

**Comment by rixrix** [comment]
@the-real-blackh published the latest version 1.0.1 to npm registry. The error that you had above were probably due to outdated type definition file, I've updated the packages version as well. thanks

**Comment by the-real-blackh** [comment]
Thank you!
