### ISSUE TITLE
Jest on Linux Mint

### ISSUE THREAD

**Issue by clinuxrulz** [SodiumFRP/sodium-typescript#62]
Having a little trouble running the tests. I'm in Linux Mint.

```
clinton@clinton-acer ~/GitHub/sodium-typescript $ npm run test

> sodiumjs@1.1.2 test /home/clinton/GitHub/sodium-typescript
> jest

● Validation Error:

  Module <rootDir>/node_modules/ts-jest/preprocessor.js in the transform option was not found.

  Configuration Documentation:
  https://facebook.github.io/jest/docs/configuration.html

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sodiumjs@1.1.2 test: `jest`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sodiumjs@1.1.2 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

```
clinton@clinton-acer ~/GitHub/sodium-typescript $ node -v
v9.4.0
clinton@clinton-acer ~/GitHub/sodium-typescript $ npm -v
5.6.0
```

**Comment by dakom** [comment]
Did you `npm install` ?

**Comment by clinuxrulz** [comment]
Yes I did. This ones not urgent. Building and everything else works, its just running the tests with jest fails. I have a Window's machine at work, and it works fine there. And it seems like one of the dependencies is used for checking which operating system we are using, maybe a config file somewhere is not doing the "I am running linux check"... just a guess.

**Comment by clinuxrulz** [comment]
More info from log file:
```
clinton@clinton-acer ~/GitHub/sodium-typescript $ cat npm-debug.log 
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/bin/npm', 'run', 'test' ]
2 info using npm@3.10.8
3 info using node@v9.4.0
4 verbose run-script [ 'pretest', 'test', 'posttest' ]
5 info lifecycle sodiumjs@1.1.2~pretest: sodiumjs@1.1.2
6 silly lifecycle sodiumjs@1.1.2~pretest: no script for pretest, continuing
7 info lifecycle sodiumjs@1.1.2~test: sodiumjs@1.1.2
8 verbose lifecycle sodiumjs@1.1.2~test: unsafe-perm in lifecycle true
9 verbose lifecycle sodiumjs@1.1.2~test: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/clinton/GitHub/sodium-typescript/node_modules/.bin:/home/clinton/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
10 verbose lifecycle sodiumjs@1.1.2~test: CWD: /home/clinton/GitHub/sodium-typescript
11 silly lifecycle sodiumjs@1.1.2~test: Args: [ '-c', 'jest' ]
12 silly lifecycle sodiumjs@1.1.2~test: Returned: code: 1  signal: null
13 info lifecycle sodiumjs@1.1.2~test: Failed to exec test script
14 verbose stack Error: sodiumjs@1.1.2 test: `jest`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at EventEmitter.emit (events.js:160:13)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at ChildProcess.emit (events.js:160:13)
14 verbose stack     at maybeClose (internal/child_process.js:943:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
15 verbose pkgid sodiumjs@1.1.2
16 verbose cwd /home/clinton/GitHub/sodium-typescript
17 error Linux 4.4.0-21-generic
18 error argv "/usr/local/bin/node" "/usr/bin/npm" "run" "test"
19 error node v9.4.0
20 error npm  v3.10.8
21 error code ELIFECYCLE
22 error sodiumjs@1.1.2 test: `jest`
22 error Exit status 1
23 error Failed at the sodiumjs@1.1.2 test script 'jest'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the sodiumjs package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     jest
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs sodiumjs
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls sodiumjs
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by dakom** [comment]
I just regenerated package-lock.json which was causing some funky errors on a fresh debian instance, but now this works perfectly for me on that instance:

1. `git clone https://github.com/SodiumFRP/sodium-typescript.git`
2. `cd sodium-typescript`
3. `npm install`
4. `npm run test`

**Comment by dakom** [comment]
The error that the regenerated package-json fixes is the one you hit here:

```
npm ERR! Command failed: /usr/bin/git checkout 276f046ad886560a2d4237c0f22159ba1107f847
npm ERR! fatal: reference is not a tree: 276f046ad886560a2d4237c0f22159ba1107f847
```

Please let me know if it's fixed now.

Btw you shouldn't have to add any packages... `npm install` itself should cover everything

**Comment by clinuxrulz** [comment]
Hey, that fixed it. :smile: Cheers!

**Comment by dakom** [comment]
Woohoo!
